Adds a Github Actions workflow for release.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,10 +29,10 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Check required secrets
-          if: ${{ !secrets.DOCKER_USERNAME || !secrets.DOCKER_PASSWORD || !secrets.DOCKER_REGISTRY }}
-          run: |
-            echo "Required Docker secrets are missing."
-            exit 1
+        if: ${{ !secrets.DOCKER_USERNAME || !secrets.DOCKER_PASSWORD || !secrets.DOCKER_REGISTRY }}
+        run: |
+          echo "Required Docker secrets are missing."
+          exit 1
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
