Adds a Github Actions workflow for release.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -23,16 +23,20 @@ on:
 jobs:
   docker:
     runs-on: ubuntu-latest
-    if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD && secrets.DOCKER_REGISTRY }}
 
     steps:
       - uses: actions/checkout@v4
 
       - name: Check required secrets
-        if: ${{ !secrets.DOCKER_USERNAME || !secrets.DOCKER_PASSWORD || !secrets.DOCKER_REGISTRY }}
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
         run: |
-          echo "Required Docker secrets are missing."
-          exit 1
+          if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ] || [ -z "$DOCKER_REGISTRY" ]; then
+            echo "Required Docker secrets are missing."
+            exit 1
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
